name: "build-test"
on:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn run all
  test_on_same_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ secrets.PA_TOKEN }}
          workflow: target.yml
          branch: main
          inputs: '{ "should_succeed" : "true" }'
  test_on_different_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ secrets.PA_TOKEN }}
          workflow: new-test-workflow.yml
          branch: foobar
          repo: "yohoo"
